# Generated by Django 2.2.9 on 2020-03-01 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20200228_1649'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notes',
            table='Notess',
        ),
    ]
