# Generated by Django 2.2.9 on 2020-03-01 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20200301_0813'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notes',
            table=None,
        ),
    ]
